<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('menu_items')->delete();

        \DB::table('menu_items')->insert([
            0 => [
                'id' => 200,
                'label' => '{"en": "Dashboard","bn": "ড্যাশবোর্ড","fr": "Tableau de bord","zh": "仪表板","ar": "لوحة القيادة","be": "Панэль прыбораў","bg": "Табло","ca": "Tauler de control","et": "Armatuurlaud","nl": "Dashboard"}',
                'link' => 'dashboard',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\VendorController@index","route_name":["vendor-dashboard"],"menu_level":"3"}',
                'is_default' => 1,
                'icon' => 'fas fa-home',
                'parent' => 0,
                'sort' => '0.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 0,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            1 => [
                'id' => 201,
                'label' => '{"en":"Orders","bn":"অর্ডার","fr":"Commandes","zh":"订单","ar":"الطلبات","be":"Замовы","bg":"Поръчки","ca":"Comandes","et":"Tellimused","nl":"Bestellingen"}',
                'link' => 'orders',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\VendorOrderController@index", "route_name":["vendorOrder.index", "vendorOrder.view", "vendorOrder.pdf", "vendorOrder.csv"], "menu_level":"3"}',
                'is_default' => 1,
                'icon' => 'fas fa-shopping-bag',
                'parent' => 0,
                'sort' => '2.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 0,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            3 => [
                'id' => 202,
                'label' => '{"en":"Withdrawals","bn":"উত্তোলন","fr":"Retraits","zh":"提款","ar":"السحب","be":"Вывядзенні","bg":"Тегления","ca":"Retirs","et":"Väljamaksed","nl":"Opnames"}',
                'link' => 'withdrawals',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\WithdrawalController@index","route_name":["vendorWithdrawal.index", "vendorWithdrawal.setting", "vendorWithdrawal.money"]}',
                'is_default' => 1,
                'icon' => 'far fa-credit-card',
                'parent' => 0,
                'sort' => '3.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 0,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            6 => [
                'id' => 203,
                'label' => '{"en":"Products","bn":"পণ্য","fr":"Produits","zh":"产品","ar":"منتجات","be":"Тавары","bg":"Продукти","ca":"Productes","et":"Tooted","nl":"Producten"}',
                'link' => null,
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\ProductController@index","route_name":["vendor.products","vendor.product.view","vendor.product.related","vendor.product.search","vendor.product.update","vendor.product.edit", "vendor.product.store", "vendor.product.create", "vendor.product.import", "vendor.itemCsv", "vendor.itemPdf", "vendor.itemDestroy", "vendor.items"]}',
                'is_default' => 0,
                'icon' => 'fas fa-cube',
                'parent' => 0,
                'sort' => '1.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 0,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            8 => [
                'id' => 204,
                'label' => '{"en":"Transactions","bn":"লেনদেন","fr":"Transactions","zh":"交易","ar":"المعاملات","be":"Транзакцыі","bg":"Транзакции","ca":"Transaccions","et":"Tehingud","nl":"Transacties"}',
                'link' => 'transactions',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\VendorTransactionController@index", "route_name":["vendorTransaction.index", "vendorTransaction.pdf", "vendorTransaction.csv"], "menu_lavel":"3"}',
                'is_default' => 1,
                'icon' => 'fas fa-exchange-alt',
                'parent' => 0,
                'sort' => '5.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 0,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            9 => [
                'id' => 205,
                'label' => '{"en":"Reports","bn":"রিপোর্ট","fr":"Rapports","zh":"报告","ar":"تقارير","be":"Справаздачы","bg":"Доклади","ca":"Informes","et":"Aruanded","nl":"Rapporten"}',
                'link' => 'reports',
                'params' => '{"permission":"Modules\\\\Report\\\\Http\\\\Controllers\\\\Vendor\\\\ReportController@index", "route_name":["vendor.reports"], "menu_level":"3"}',
                'is_default' => 1,
                'icon' => 'fas fa-chart-bar',
                'parent' => 0,
                'sort' => '10.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 0,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            10 => [
                'id' => 206,
                'label' => '{"en":"Tickets","bn":"টিকিট","fr":"Tickets","zh":"票","ar":"تذاكر","be":"Квіткі","bg":"Билети","ca":"Tiquets","et":"Piletid","nl":"Tickets"}',
                'link' => 'ticket/list',
                'params' => '{"permission":"Modules\\\\Ticket\\\\Http\\\\Controllers\\\\Vendor\\\\TicketController@index", "route_name":["vendor.threads", "vendor.threadAdd", "vendor.threadReply", "vendor.threadPdf", "vendor.threadCsv"]}',
                'is_default' => 1,
                'icon' => 'fas fa-ticket-alt',
                'parent' => 0,
                'sort' => '11.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 0,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            11 => [
                'id' => 207,
                'label' => '{"en":"Import Products","bn":"পণ্য আমদানি করুন","fr":"Importer des produits","zh":"导入产品","ar":"استيراد المنتجات","be":"Імпартаваць прадукцыю","bg":"Импортиране на продукти","ca":"Importar productes","et":"Impordi tooteid","nl":"Producten importeren"}',
                'link' => 'import/products',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\ImportController@productImport", "route_name":["vendor.epz.import.products"], "menu_level":"3"}',
                'is_default' => 1,
                'icon' => 'fas fa-download',
                'parent' => 203,
                'sort' => '7.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 0,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            12 => [
                'id' => 208,
                'label' => '{"en":"Export Products","bn":"পণ্য রফতানি করুন","fr":"Exporter des produits","zh":"导出产品","ar":"تصدير المنتجات","be":"Экспарт прадукцыі","bg":"Изнасяне на продукти","ca":"Exportar productes","et":"Eksportige tooteid","nl":"Producten exporteren"}',
                'link' => 'export/products',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\ExportController@productExport", "route_name":["vendor.epz.export.products"], "menu_level":"3"}',
                'is_default' => 1,
                'icon' => 'fas fa-download',
                'parent' => 203,
                'sort' => '6.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 1,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            13 => [
                'id' => 209,
                'label' => '{"en":"Customers","bn":"গ্রাহকদের","fr":"Clients","zh":"客户","ar":"العملاء","be":"Кліенты","bg":"Клиенти","ca":"Clients","et":"Kliendid","nl":"Klanten"}',
                'link' => 'customer',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\CustomerController@index", "route_name":["vendor.customer", "vendor.customer.create"], "menu_level":"3"}',
                'is_default' => 1,
                'icon' => 'fas fa-users',
                'parent' => 0,
                'sort' => '3.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 0,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            15 => [
                'id' => 210,
                'label' => '{"en":"Barcode","bn":"বারকোড","fr":"Code-barres","zh":"条码","ar":"الباركود","be":"Штрых-код","bg":"Баркод","ca":"Codi de barres","et":"Vöötkood","nl":"Barcode"}',
                'link' => 'barcode/product',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\BarcodeController@product","route_name":["vendor.barcode.product"]}',
                'is_default' => 1,
                'icon' => 'fas fa-barcode',
                'parent' => 203,
                'sort' => '2.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 0,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            16 => [
                'id' => 211,
                'label' => '{"en":"Categories","bn":"বিভাগ","fr":"Catégories","zh":"类别","ar":"فئات","be":"Катэгорыі","bg":"Категории","ca":"Categories","et":"Kategooriad","nl":"Categorieën"}',
                'link' => 'all-categories',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\CategoryController@index","route_name":["vendor.categories.index"], "menu_level":"3"}',
                'is_default' => 1,
                'icon' => 'fas fa-align-left',
                'parent' => 203,
                'sort' => '3.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 0,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            17 => [
                'id' => 212,
                'label' => 'Staff',
                'link' => 'staffs',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\StaffController@index", "route_name":["vendor.staffs.index", "vendor.staffs.create", "vendor.staffs.edit", "vendor.roles.index", "vendor.roles.create", "vendor.roles.edit", "vendor.permission.index"]}',
                'is_default' => 1,
                'icon' => 'fas fa-users',
                'parent' => 0,
                'sort' => '3.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 0,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            18 => [
                'id' => 213,
                'label' => '{"en":"Brands","bn":"ব্র্যান্ড","fr":"Marques","zh":"品牌","ar":"العلامات التجارية","be":"Брэнды","bg":"Марки","ca":"Marques","et":"Brändid","nl":"Merken"}',
                'link' => 'all-brands',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\BrandController@index", "route_name":["vendor.brands.index", "vendor.brands.create", "vendor.brands.edit", "vendor.brands.store", "vendor.brands.destroy"]}',
                'is_default' => 1,
                'icon' => 'fas fa-file',
                'parent' => 203,
                'sort' => '3.10000000',
                'class' => null,
                'menu' => 4,
                'depth' => 0,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            19 => [
                'id' => 214,
                'label' => '{"en":"Attributes","bn":"গুণগুলি","fr":"Attributs","zh":"属性","ar":"السمات","be":"Атрыбуты","bg":"Атрибути","ca":"Atributs","et":"Atribuudid","nl":"Eigenschappen"}',
                'link' => 'all-attributes',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\AttributeController@index", "route_name":["vendor.attribute.index", "vendor.attribute.create", "vendor.attribute.edit", "vendor.attribute.store", "vendor.attribute.destroy"]}',
                'is_default' => 1,
                'icon' => 'fas fa-list-alt',
                'parent' => 203,
                'sort' => '3.20000000',
                'class' => null,
                'menu' => 4,
                'depth' => 0,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            20 => [
                'id' => 215,
                'label' => '{"en":"Inventory","bn":"মজুদ","fr":"Inventaire","zh":"库存","ar":"المخزون","be":"Сток","bg":"Наличност","ca":"Inventari","et":"Varu","nl":"Voorraad"}',
                'link' => null,
                'params' => '',
                'is_default' => 0,
                'icon' => 'fas fa-table',
                'parent' => 0,
                'sort' => '2.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 0,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            21 => [
                'id' => 216,
                'label' => '{"en":"Location","bn":"অবস্থান","fr":"Emplacement","zh":"位置","ar":"الموقع","be":"Месцазнаходжанне","bg":"Местоположение","ca":"Ubicació","et":"Asukoht","nl":"Locatie"}',
                'link' => 'inventory/location',
                'params' => '{"permission":"Modules\\\\Inventory\\\\Http\\\\Controllers\\\\Vendor\\\\LocationController@index","route_name":["vendor.location.index", "vendor.location.edit", "vendor.location.create", "vendor.location.store", "vendor.location.update", "vendor.location.destroy"]}',
                'is_default' => 1,
                'icon' => null,
                'parent' => 166,
                'sort' => '2.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 1,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            22 => [
                'id' => 217,
                'label' => '{"en":"Supplier","bn":"সরবরাহকারী","fr":"Fournisseur","zh":"供应商","ar":"المورد","be":"Пастаўшчык","bg":"Доставчик","ca":"Proveïdor","et":"Tarnija","nl":"Leverancier"}',
                'link' => 'inventory/supplier',
                'params' => '{"permission":"Modules\\\\Inventory\\\\Http\\\\Controllers\\\\Vendor\\\\SupplierController@index","route_name":["vendor.supplier.index", "vendor.supplier.edit", "vendor.supplier.create", "vendor.supplier.store", "vendor.supplier.update", "vendor.supplier.destroy"]}',
                'is_default' => 1,
                'icon' => null,
                'parent' => 166,
                'sort' => '2.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 1,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            23 => [
                'id' => 218,
                'label' => '{"en":"Transaction","bn":"লেনদেন","fr":"Transaction","zh":"交易","ar":"المعاملة","be":"Трансакцыя","bg":"Транзакция","ca":"Transacció","et":"Tehing","nl":"Transactie"}',
                'link' => 'inventory/transaction',
                'params' => '{"permission":"Modules\\\\Inventory\\\\Http\\\\Controllers\\\\Vendor\\\\InventoryController@transaction","route_name":["vendor.inventory.transaction"]}',
                'is_default' => 1,
                'icon' => null,
                'parent' => 166,
                'sort' => '7.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 1,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            24 => [
                'id' => 219,
                'label' => '{"en":"Purchase Order","bn":"ক্রয় আদেশ","fr":"Bon de commande","zh":"采购订单","ar":"طلب الشراء","be":"Заказ","bg":"Поръчка","ca":"Ordre de compra","et":"Tellimus","nl":"Aankooporder"}',
                'link' => 'inventory/purchase-order',
                'params' => '{"permission":"Modules\\\\Inventory\\\\Http\\\\Controllers\\\\Vendor\\\\PurchaseController@index","route_name":["vendor.purchase.index", "vendor.purchase.edit", "vendor.purchase.create", "vendor.purchase.store", "vendor.purchase.update", "vendor.purchase.destroy", "vendor.purchase.receive"]}',
                'is_default' => 1,
                'icon' => null,
                'parent' => 166,
                'sort' => '4.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 1,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            25 => [
                'id' => 220,
                'label' => '{"en":"Stock","bn":"স্টক","fr":"Stock","zh":"股票","ar":"المخزون","be":"Запас","bg":"Акции","ca":"Estoc","et":"Aksiad","nl":"Voorraad"}',
                'link' => 'inventory',
                'params' => '{"permission":"Modules\\\\Inventory\\\\Http\\\\Controllers\\\\Vendor\\\\InventoryController@index","route_name":["vendor.inventory.index", "vendor.inventory.adjust"]}',
                'is_default' => 1,
                'icon' => null,
                'parent' => 166,
                'sort' => '5.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 1,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            26 => [
                'id' => 221,
                'label' => '{"en":"Transfer","bn":"স্থানান্তর","fr":"Transfert","zh":"转账","ar":"تحويل","be":"Перанос","bg":"Трансфер","ca":"Transferència","et":"Ülekanne","nl":"Overdracht"}',
                'link' => 'inventory/transfer',
                'params' => '{"permission":"Modules\\\\Inventory\\\\Http\\\\Controllers\\\\Vendor\\\\TransferController@index","route_name":["vendor.transfer.index", "vendor.transfer.create", "vendor.transfer.edit", "vendor.transfer.receive"]}',
                'is_default' => 1,
                'icon' => null,
                'parent' => 166,
                'sort' => '6.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 1,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => '2025-07-15 06:36:31',
            ],
            27 => [
                'id' => 222,
                'label' => 'POS',
                'link' => null,
                'params' => null,
                'is_default' => 1,
                'icon' => 'fas fa-desktop',
                'parent' => 0,
                'sort' => '4.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 0,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            28 => [
                'id' => 223,
                'label' => 'Setup',
                'link' => 'pos/setup',
                'params' => '{"permission":"Modules\\\\Pos\\\\Http\\\\Controllers\\\\Vendor\\\\POSController@setup", "route_name":["vendor.pos.setup", "vendor.pos.receipt", "vendor.pos.payment_method", "vendor.pos.discount"]}',
                'is_default' => 1,
                'icon' => null,
                'parent' => 176,
                'sort' => '1.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 1,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            29 => [
                'id' => 224,
                'label' => 'Terminals',
                'link' => 'pos/terminals',
                'params' => '{"permission":"Modules\\\\Pos\\\\Http\\\\Controllers\\\\Vendor\\\\TerminalController@index", "route_name":["vendor.pos.terminals.index", "vendor.pos.terminals.create", "vendor.pos.terminals.edit", "vendor.pos.terminals.history"]}',
                'is_default' => 1,
                'icon' => null,
                'parent' => 176,
                'sort' => '2.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 1,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            30 => [
                'id' => 225,
                'label' => 'Orders',
                'link' => 'pos/orders',
                'params' => '{"permission":"Modules\\\\Pos\\\\Http\\\\Controllers\\\\Vendor\\\\OrderController@index", "route_name":["vendor.pos.orders.index"]}',
                'is_default' => 1,
                'icon' => null,
                'parent' => 176,
                'sort' => '3.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 1,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            31 => [
                'id' => 226,
                'label' => 'Staff Activities',
                'link' => 'pos/activities',
                'params' => '{"permission":"Modules\\\\Pos\\\\Http\\\\Controllers\\\\Vendor\\\\ActivityController@index", "route_name":["vendor.pos.activities.index"]}',
                'is_default' => 1,
                'icon' => null,
                'parent' => 176,
                'sort' => '4.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 1,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            32 => [
                'id' => 227,
                'label' => 'Subscriptions',
                'link' => 'subscription',
                'params' => '{"permission":"Modules\\\\Subscription\\\\Http\\\\Controllers\\\\Vendor\\\\SubscriptionController@index","route_name":["vendor.subscription.index", "vendor.subscription.store", "vendor.subscription.paid", "vendor.subscription.history", "vendor.subscription.invoice"]}',
                'is_default' => 1,
                'icon' => 'fas fa-money-bill-alt',
                'parent' => 0,
                'sort' => '4.00000000',
                'class' => null,
                'menu' => 4,
                'depth' => 0,
                'is_custom_menu' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
        ]);


    }
}
